ALTER TABLE `OpsIssue`
    MODIFY `issueType` ENUM(
        'DATA_DISPUTE',
        'WRONG_SCORE',
        'BROKEN_ARTICLE_CONTENT',
        'BROKEN_AFFILIATE_DESTINATION',
        'PROVIDER_SWITCH_INCIDENT',
        'COMPLIANCE_INCIDENT'
    ) NOT NULL;
